/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {

        Director director = new Director();
        Product product = director.construct();
        System.out.println(product.parts);

        FluentBuilder fluentBuilder = new FluentBuilder();
        Product motorcycle = fluentBuilder.begin()
            .engine()
            .steeringWheel()
            .tire()
            .tire()
            .build();
        System.out.println(motorcycle.parts);

        FluentBuilderFunctions fnBuilder = new FluentBuilderFunctions();
        Product atv = fnBuilder.begin()
            .engine()
            .steeringWheel()
            .tire(4)
            .end();
        System.out.println(atv.parts);
    }
}
