/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        // Create a singleton instance
        SingletonV1 singleton = SingletonV1.getInstance();
        singleton.doSomething();

        // Verify that the same instance is returned
        SingletonV1 anotherInstance = SingletonV1.getInstance();
        System.out.println("Are both instances the same? " + (singleton == anotherInstance));

        // Create a singleton instance
        SingletonV3 s2 = SingletonV3.getInstance();
        s2.doSomething();

        // Verify that the same instance is returned
        SingletonV3 ai2 = SingletonV3.getInstance();
        System.out.println("Are both instances the same? " + (s2 == ai2));
    }
}
